### ISSUE TITLE
Installation Timeout Error

### ISSUE THREAD

**Issue by CarlOgden1967** [ralphjsmit/tall-install#6]
Hi

Following your instructions, when I perform

php artisan tall-install, I get the following error

`
ralph-example laravel$ php artisan tall-install -b -d
Preparing installation
Installing Alpine

   Symfony\Component\Process\Exception\ProcessTimedOutException 

  The process "'npm' 'install' 'alpinejs' '@alpinejs/focus' '--save-dev'" exceeded the timeout of 60 seconds.

  at vendor/symfony/process/Process.php:1152
    1148▕ 
    1149▕         if (null !== $this->timeout && $this->timeout < microtime(true) - $this->starttime) {
    1150▕             $this->stop(0);
    1151▕ 
  ➜ 1152▕             throw new ProcessTimedOutException($this, ProcessTimedOutException::TYPE_GENERAL);
    1153▕         }
    1154▕ 
    1155▕         if (null !== $this->idleTimeout && $this->idleTimeout < microtime(true) - $this->lastOutputTime) {
    1156▕             $this->stop(0);

      +20 vendor frames 
  21  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
`

Any idea of what the issue is? 

Kind regards
Carl

**Comment by ralphjsmit** [comment]
Hey Carl, thanks for your message! I think that installing the NPM packages took longer than 60 seconds, which caused an timeout error. 

I now set the allowed timeout to 240s, so that it will allow up to 240s for installing the NPM and Composer packages. This has been released in 1.3.1.

Thanks for reporting this! I'll close this, since I released an update. Might the fix not be sufficient and it still happens to you, feel free to comment/reopen again.
